---
- name: Testing Okta modules
  hosts: localhost
  tasks:

    - name: List users in Okta organization
      okta_users:
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
      register: users

    - name: Print users
      debug:
        msg: "{{ users.json }}"

    - name: List apps in Okta organization
      okta_apps_swa:
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
      register: apps

    - name: Print apps
      debug:
        msg: "{{ apps.json }}"
