---
- name: Testing Okta modules
  hosts: localhost
  tasks:

    - name: Create Okta group
      okta_groups:
        action: "create"
        name: "Test"
        description: ""
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
      register: okta_group

    - name: Print group information
      debug:
        msg: "{{ okta_group.json.id }}"

    - name: Create Okta user
      okta_users:
        action: create
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
        login: "whitney.ellis.champion@gmail.com"
        first_name: "Whitney"
        last_name: "Champion"
        activate: true
        password: "{{ password }}"
        group_ids:
          - "{{ okta_group.json.id }}"
        email: "whitney.ellis.champion@gmail.com"
      register: okta_user

    - name: Print user information
      debug:
        msg: "{{ okta_user.json.id }}"

    - name: Update Okta user
      okta_users:
        action: update
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
        id: "{{ okta_user.json.id }}"
        email: "whitney.ellis.champion+new@gmail.com"
      register: okta_user

    - name: Print user information
      debug:
        msg: "{{ okta_user.json.id }}"

    - name: Create Okta app
      okta_apps_swa:
        action: create
        label: "Ansible Test"
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
        login_url: "https://unicorns.lol/login"
        redirect_url: "https://unicorns.lol/redirect"
      register: okta_app

    - name: Print app information
      debug:
        msg: "{{ okta_app.json.id }}"

    - name: Activate Okta app
      okta_apps_swa:
        action: activate
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
        id: "{{ okta_app.json.id }}"

    - name: Assign new app to new group
      okta_apps_swa:
        action: assign_group
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
        id: "{{ okta_app.json.id }}"
        group_id: "{{ okta_group.json.id }}"
      register: okta_assignment

    - name: Remove user from group
      okta_groups:
        action: remove_user
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
        id: "{{ okta_group.json.id }}"
        user_id: "{{ okta_user.json.id }}"

    - name: Remove group from app
      okta_apps_swa:
        action: remove_group
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
        id: "{{ okta_app.json.id }}"
        group_id: "{{ okta_group.json.id }}"

    - name: Remove group
      okta_groups:
        action: delete
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
        id: "{{ okta_group.json.id }}"

    - name: Remove user
      okta_users:
        action: delete
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
        id: "{{ okta_user.json.id }}"

    - name: Remove app
      okta_apps_swa:
        action: delete
        organization: "{{ organization }}"
        api_key: "{{ api_key }}"
        id: "{{ okta_app.json.id }}"
